export default {
  /** LOGIN PAGE ACTION TYPE */
  GENDER: 'GENDER',
  CHILD_DOB: 'CHILD_DOB',
  ADD_CHILD: 'ADD_CHILD',
  CHILD_NAME: 'CHILD_NAME',
  LOGIN_DETAILS: 'LOGIN_DETAILS',
  SIGNUP_DETAILS: 'SIGNUP_DETAILS',
  CHILD_LOCATION: 'CHILD_LOCATION',
  CHILD_SCHOOLNAME: 'CHILD_SCHOOLNAME',
  LANGUAGE_INTERSTED: 'LANGUAGE_INTERSTED',
  LANGUAGE_SPOKEN: ' LANGUAGE_SPOKEN',
  INTERESTED: 'INTERESTED',
  UPDATE_INTERNET_FIELDS: 'UPDATE_INTERNET_FIELDS',
  CHILD_PROFILE_IMAGE: 'CHILD_PROFILE_IMAGE',
};
