export default {
  /** LOGIN PAGE ACTION TYPE */
  GENDER: 'GENDER',
  CHILD_DOB: 'CHILD_DOB',
  CHILD_NAME: 'CHILD_NAME',
  LOGIN_DETAILS: 'LOGIN_DETAILS',
  SIGNUP_DETAILS: 'SIGNUP_DETAILS',
  CHILD_LOCATION: 'CHILD_LOCATION',
  CHILD_SCHOOLNAME: 'CHILD_SCHOOLNAME',
  CHILD_PROFILE_IMAGE: 'CHILD_PROFILE_IMAGE',
};
