export default {
  fbIcon: require('../assets/images/fb.png'),
  eyeIcon: require('../assets/images/eye.png'),
  backIcon: require('../assets/images/back.png'),
  editIcon: require('../assets/images/edit.png'),
  nameIcon: require('../assets/images/name.png'),
  demoDp: require('../assets/images/demoDp.png'),
  mailIcon: require('../assets/images/mail.png'),
  appleIcon: require('../assets/images/apple.png'),
  googleIcon: require('../assets/images/google.png'),
  sampleImg2: require('../assets/images/sample2.png'),
  sampleImg1: require('../assets/images/sample1.png'),
  seachIcon: require('../assets/images/ic-search.png'),
  heartIcon: require('../assets/images/heartIcon.png'),
  background: require('../assets/images/background.png'),
  passwordIcon: require('../assets/images/password.png'),
  profileIcon: require('../assets/images/ic_profile.png'),
  hiddenEyeIcon: require('../assets/images/eyeHidden.png'),
  homeActiveIcon: require('../assets/images/homeActive.png'),
  horiztontalIcon: require('../assets/images/horizontalIcon.png'),
  backgroundWhite: require('../assets/images/backgroundWhite.png'),
  heartActiveIcon: require('../assets/images/iconHeartActive.png'),
};
