export default {
  HOME: 'Home',
  BOOKS: 'Books',
  LOG_IN: 'Login',
  SIGN_UP: 'SignUp',
  WRITING: 'Writing',
  ON_BOARD: 'Onboard',
  MY_BOOKS: 'My Books',
  ADD_CHILD: 'AddChild',
  APPOINTMENTS: 'Appointments',
  BASIC_DETAILS: 'BasicDetails',
  FORGET_PASS: 'ForgetPassword',
  BOTTOM_TAB: 'BottomTabNavigator',
  CHILD_NAMES: 'ChildName',
  INTERESTED: 'Interested',
  LANG_INTEREST: 'langInterest',
  LANG_SPOKEN: 'LangSpoken',
  SET_MPIN: 'SetMpin',
  CONFIRM_MPIN: 'ConfirmMpin',
  SUCCESS: 'Success',
};
