/**
 * @description contains all the constant strings here
 */

export default {
  hey: 'Hi',
  boy: 'Boy',
  girl: 'Girl',
  next: 'Next',
  skip: 'Skip',
  name: 'Name',
  login: 'Log In',
  school: 'School',
  gender: 'Gender',
  google: 'Google',
  pass: 'Password',
  signup: ' Sign Up',
  welcome: 'Welcome',
  sucess: 'Success',
  interset: 'Interest',
  DOB: 'Date of Birth',
  location: 'Location',
  facebook: 'Facebook',
  setMpin: 'Set M-Pin',
  addChild: 'Add Child',
  email: 'Email Address',
  discussion: 'Discussion',
  welcomeBack: 'Welcome back',
  placeholder: 'Write comment',
  basicDetails: 'Basic Details',
  confirmMpin: 'Confirm M-Pin',
  errorCode404: 'Page not found',
  errorCode410: 'User not found',
  errorCode408: 'Request Timeout',
  errorName: 'Please Enter Valid Name',
  forgetPass: 'Forgot Password?',
  languageSpoken: 'Language Spoken',
  loginSucess: 'Login Sucessfully',
  seachlanguage: 'Search by languages',
  errorLocation: 'Please Enter Valid location',
  errorDOB: 'Please Enter Valid Date Of Birth',
  profilePicUpdated: 'ProfilePicUpload',
  enterPassword: 'Password must be enter',
  errorCode401: 'Credentials are not valid',
  languageInterested: 'Language Interested',
  errorSchoolName: 'Please Enter Valid School Name',
  dontHaveAccount: 'Do you have an account?',
  enterValidPassword: 'Enter valid password',
  continueWithApple: 'Continue with Apple ID',
  loginToAccess: 'Login to access your account',
  enterValidCreditials: 'Enter Valid Creditials',
  networkErrorCode: 'Please connect to internet',
  errorCode422: "server can't process your request",
  enterEmailAddress: 'Email address must be enter',
  enterValidEmailAddress: 'Enter valid email address',
  showEmptyFieldError: 'Please Enter all the required field',
  signupDescription:
    'A wonderful platform for children to read  and collaborate with teacher!',
  forgetDescription:
    'Enter your registered email ID and we will send a link to reset password',
  addChildDescription:
    'Add child who always want to access the eBooks and collaborate with teachers',
  basicDetailDescription:
    'Lets start with some basic information of your child',
  setMpinDescription:
    'The pin you set here will get associated with your profile. The pin will b emailed you as well.',
  labguageIntrestedDescription: `Tell us more about what languages  is interested in`,
};
